'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.34209
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

Namespace LibRechCandidat


    '
    'This source code was auto-generated by xsd, Version=4.0.30319.17929.
    '

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/CLIENTSchema.xsd"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://tempuri.org/CLIENTSchema.xsd", IsNullable:=False)> _
    Partial Public Class VACANCY

        Private languageField As String

        Private jobTitleField As String

        Private locationField As String

        Private referenceNumberField As String

        Private postingDateField As String

        Private applicationDeadlineField As String

        Private startDateField As String

        Private numberOfOpeningsField As String

        Private organizationField As Organization

        Private candidateRequirementsField As CandidateRequirements

        Private conditionsBenefitsField As ConditionsBenefits

        Private sectionsField As Sections

        Private vacancyTextField As String

        Private userAreaField As UserArea

        '''<remarks/>
        Public Property Language() As String
            Get
                Return Me.languageField
            End Get
            Set(value As String)
                Me.languageField = value
            End Set
        End Property

        '''<remarks/>
        Public Property JobTitle() As String
            Get
                Return Me.jobTitleField
            End Get
            Set(value As String)
                Me.jobTitleField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Location() As String
            Get
                Return Me.locationField
            End Get
            Set(value As String)
                Me.locationField = value
            End Set
        End Property

        '''<remarks/>
        Public Property ReferenceNumber() As String
            Get
                Return Me.referenceNumberField
            End Get
            Set(value As String)
                Me.referenceNumberField = value
            End Set
        End Property

        '''<remarks/>
        Public Property PostingDate() As String
            Get
                Return Me.postingDateField
            End Get
            Set(value As String)
                Me.postingDateField = value
            End Set
        End Property

        '''<remarks/>
        Public Property ApplicationDeadline() As String
            Get
                Return Me.applicationDeadlineField
            End Get
            Set(value As String)
                Me.applicationDeadlineField = value
            End Set
        End Property

        '''<remarks/>
        Public Property StartDate() As String
            Get
                Return Me.startDateField
            End Get
            Set(value As String)
                Me.startDateField = value
            End Set
        End Property

        '''<remarks/>
        Public Property NumberOfOpenings() As String
            Get
                Return Me.numberOfOpeningsField
            End Get
            Set(value As String)
                Me.numberOfOpeningsField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Organization() As Organization
            Get
                Return Me.organizationField
            End Get
            Set(value As Organization)
                Me.organizationField = value
            End Set
        End Property

        '''<remarks/>
        Public Property CandidateRequirements() As CandidateRequirements
            Get
                Return Me.candidateRequirementsField
            End Get
            Set(value As CandidateRequirements)
                Me.candidateRequirementsField = value
            End Set
        End Property

        '''<remarks/>
        Public Property ConditionsBenefits() As ConditionsBenefits
            Get
                Return Me.conditionsBenefitsField
            End Get
            Set(value As ConditionsBenefits)
                Me.conditionsBenefitsField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Sections() As Sections
            Get
                Return Me.sectionsField
            End Get
            Set(value As Sections)
                Me.sectionsField = value
            End Set
        End Property

        '''<remarks/>
        Public Property VacancyText() As String
            Get
                Return Me.vacancyTextField
            End Get
            Set(value As String)
                Me.vacancyTextField = value
            End Set
        End Property

        '''<remarks/>
        Public Property UserArea() As UserArea
            Get
                Return Me.userAreaField
            End Get
            Set(value As UserArea)
                Me.userAreaField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/CLIENTSchema.xsd")> _
    Partial Public Class Organization

        Private nameField As String

        Private addressField As String

        Private phoneField As String

        Private emailField As String

        Private faxField As String

        Private websiteField As String

        Private contactPersonField As String

        Private industryField As String

        '''<remarks/>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set(value As String)
                Me.nameField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Address() As String
            Get
                Return Me.addressField
            End Get
            Set(value As String)
                Me.addressField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Phone() As String
            Get
                Return Me.phoneField
            End Get
            Set(value As String)
                Me.phoneField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Email() As String
            Get
                Return Me.emailField
            End Get
            Set(value As String)
                Me.emailField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Fax() As String
            Get
                Return Me.faxField
            End Get
            Set(value As String)
                Me.faxField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Website() As String
            Get
                Return Me.websiteField
            End Get
            Set(value As String)
                Me.websiteField = value
            End Set
        End Property

        '''<remarks/>
        Public Property ContactPerson() As String
            Get
                Return Me.contactPersonField
            End Get
            Set(value As String)
                Me.contactPersonField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Industry() As String
            Get
                Return Me.industryField
            End Get
            Set(value As String)
                Me.industryField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/CLIENTSchema.xsd")> _
    Partial Public Class Referentiel

        Private codeField As String

        Private libelleField As String

        '''<remarks/>
        Public Property code() As String
            Get
                Return Me.codeField
            End Get
            Set(value As String)
                Me.codeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property libelle() As String
            Get
                Return Me.libelleField
            End Get
            Set(value As String)
                Me.libelleField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/CLIENTSchema.xsd")> _
    Partial Public Class Adresse

        Private ligne1Field As String

        Private ligne2Field As String

        Private ligne3Field As String

        Private ligne4Field As String

        Private latitudeField As CritereFloat

        Private longitudeField As CritereFloat

        Private prioriteField As Integer

        Private prioriteFieldSpecified As Boolean

        '''<remarks/>
        Public Property ligne1() As String
            Get
                Return Me.ligne1Field
            End Get
            Set(value As String)
                Me.ligne1Field = value
            End Set
        End Property

        '''<remarks/>
        Public Property ligne2() As String
            Get
                Return Me.ligne2Field
            End Get
            Set(value As String)
                Me.ligne2Field = value
            End Set
        End Property

        '''<remarks/>
        Public Property ligne3() As String
            Get
                Return Me.ligne3Field
            End Get
            Set(value As String)
                Me.ligne3Field = value
            End Set
        End Property

        '''<remarks/>
        Public Property ligne4() As String
            Get
                Return Me.ligne4Field
            End Get
            Set(value As String)
                Me.ligne4Field = value
            End Set
        End Property

        '''<remarks/>
        Public Property latitude() As CritereFloat
            Get
                Return Me.latitudeField
            End Get
            Set(value As CritereFloat)
                Me.latitudeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property longitude() As CritereFloat
            Get
                Return Me.longitudeField
            End Get
            Set(value As CritereFloat)
                Me.longitudeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property priorite() As Integer
            Get
                Return Me.prioriteField
            End Get
            Set(value As Integer)
                Me.prioriteField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property prioriteSpecified() As Boolean
            Get
                Return Me.prioriteFieldSpecified
            End Get
            Set(value As Boolean)
                Me.prioriteFieldSpecified = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/CLIENTSchema.xsd")> _
    Partial Public Class CritereFloat

        Private nombreField As Single

        Private nombreFieldSpecified As Boolean

        Private prioriteField As Integer

        Private prioriteFieldSpecified As Boolean

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property nombre() As Single
            Get
                Return Me.nombreField
            End Get
            Set(value As Single)
                Me.nombreField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property nombreSpecified() As Boolean
            Get
                Return Me.nombreFieldSpecified
            End Get
            Set(value As Boolean)
                Me.nombreFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property priorite() As Integer
            Get
                Return Me.prioriteField
            End Get
            Set(value As Integer)
                Me.prioriteField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property prioriteSpecified() As Boolean
            Get
                Return Me.prioriteFieldSpecified
            End Get
            Set(value As Boolean)
                Me.prioriteFieldSpecified = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/CLIENTSchema.xsd")> _
    Partial Public Class Compte

        Private matriculeCliField As String

        Private nomField As String

        Private sigleField As String

        '''<remarks/>
        Public Property matriculeCli() As String
            Get
                Return Me.matriculeCliField
            End Get
            Set(value As String)
                Me.matriculeCliField = value
            End Set
        End Property

        '''<remarks/>
        Public Property nom() As String
            Get
                Return Me.nomField
            End Get
            Set(value As String)
                Me.nomField = value
            End Set
        End Property

        '''<remarks/>
        Public Property sigle() As String
            Get
                Return Me.sigleField
            End Get
            Set(value As String)
                Me.sigleField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/CLIENTSchema.xsd")> _
    Partial Public Class CritereHabilitation

        Private prioriteField As Integer

        Private codeField As String

        Private libelleField As String

        Private date_de_validiteField As Date

        '''<remarks/>
        Public Property priorite() As Integer
            Get
                Return Me.prioriteField
            End Get
            Set(value As Integer)
                Me.prioriteField = value
            End Set
        End Property

        '''<remarks/>
        Public Property code() As String
            Get
                Return Me.codeField
            End Get
            Set(value As String)
                Me.codeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property libelle() As String
            Get
                Return Me.libelleField
            End Get
            Set(value As String)
                Me.libelleField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")> _
        Public Property date_de_validite() As Date
            Get
                Return Me.date_de_validiteField
            End Get
            Set(value As Date)
                Me.date_de_validiteField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/CLIENTSchema.xsd")> _
    Partial Public Class CritereDiplome

        Private prioriteField As Integer

        Private codeField As String

        Private libelleField As String

        Private obtenuField As Boolean

        '''<remarks/>
        Public Property priorite() As Integer
            Get
                Return Me.prioriteField
            End Get
            Set(value As Integer)
                Me.prioriteField = value
            End Set
        End Property

        '''<remarks/>
        Public Property code() As String
            Get
                Return Me.codeField
            End Get
            Set(value As String)
                Me.codeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property libelle() As String
            Get
                Return Me.libelleField
            End Get
            Set(value As String)
                Me.libelleField = value
            End Set
        End Property

        '''<remarks/>
        Public Property obtenu() As Boolean
            Get
                Return Me.obtenuField
            End Get
            Set(value As Boolean)
                Me.obtenuField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/CLIENTSchema.xsd")> _
    Partial Public Class CritereDate

        Private dateField As Date

        Private dateFieldSpecified As Boolean

        Private prioriteField As Integer

        Private prioriteFieldSpecified As Boolean

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="date")> _
        Public Property [date]() As Date
            Get
                Return Me.dateField
            End Get
            Set(value As Date)
                Me.dateField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property dateSpecified() As Boolean
            Get
                Return Me.dateFieldSpecified
            End Get
            Set(value As Boolean)
                Me.dateFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property priorite() As Integer
            Get
                Return Me.prioriteField
            End Get
            Set(value As Integer)
                Me.prioriteField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property prioriteSpecified() As Boolean
            Get
                Return Me.prioriteFieldSpecified
            End Get
            Set(value As Boolean)
                Me.prioriteFieldSpecified = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/CLIENTSchema.xsd")> _
    Partial Public Class CritereReferentiel

        Private prioriteField As Integer

        Private codeField As String

        Private libelleField As String

        '''<remarks/>
        Public Property priorite() As Integer
            Get
                Return Me.prioriteField
            End Get
            Set(value As Integer)
                Me.prioriteField = value
            End Set
        End Property

        '''<remarks/>
        Public Property code() As String
            Get
                Return Me.codeField
            End Get
            Set(value As String)
                Me.codeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property libelle() As String
            Get
                Return Me.libelleField
            End Get
            Set(value As String)
                Me.libelleField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/CLIENTSchema.xsd")> _
    Partial Public Class CritereFlag

        Private flagField As Boolean

        Private flagFieldSpecified As Boolean

        Private prioriteField As Integer

        Private prioriteFieldSpecified As Boolean

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property flag() As Boolean
            Get
                Return Me.flagField
            End Get
            Set(value As Boolean)
                Me.flagField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property flagSpecified() As Boolean
            Get
                Return Me.flagFieldSpecified
            End Get
            Set(value As Boolean)
                Me.flagFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property priorite() As Integer
            Get
                Return Me.prioriteField
            End Get
            Set(value As Integer)
                Me.prioriteField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property prioriteSpecified() As Boolean
            Get
                Return Me.prioriteFieldSpecified
            End Get
            Set(value As Boolean)
                Me.prioriteFieldSpecified = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/CLIENTSchema.xsd")> _
    Partial Public Class UserArea

        Private dossier_completField As CritereFlag

        Private qualificationField As CritereReferentiel

        Private contracttypeField As CritereReferentiel

        Private niveau_etudeField As CritereReferentiel

        Private metierField As CritereReferentiel

        Private mobiliteField() As CritereReferentiel

        Private date_debutField As CritereDate

        Private date_finField As CritereDate

        Private permisField As CritereReferentiel

        Private competenceField() As CritereReferentiel

        Private annees_experienceField As CritereFloat

        Private clientField As CritereReferentiel

        Private secteurField As CritereReferentiel

        Private serviceField As CritereReferentiel

        Private regroupementField As CritereReferentiel

        Private diplomeField As CritereDiplome

        Private habilitationField() As CritereHabilitation

        Private langueField() As CritereReferentiel

        Private visite_medicale_a_jourField As CritereDate

        Private statut_cdi_ttField As CritereFlag

        Private tt_400hField As CritereFlag

        Private fspiField As CritereFlag

        Private compteField As Compte

        Private adresse_delegationField As Adresse

        Private cp_communeField As Referentiel

        '''<remarks/>
        Public Property dossier_complet() As CritereFlag
            Get
                Return Me.dossier_completField
            End Get
            Set(value As CritereFlag)
                Me.dossier_completField = value
            End Set
        End Property

        '''<remarks/>
        Public Property qualification() As CritereReferentiel
            Get
                Return Me.qualificationField
            End Get
            Set(value As CritereReferentiel)
                Me.qualificationField = value
            End Set
        End Property

        '''<remarks/>
        Public Property contracttype() As CritereReferentiel
            Get
                Return Me.contracttypeField
            End Get
            Set(value As CritereReferentiel)
                Me.contracttypeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property niveau_etude() As CritereReferentiel
            Get
                Return Me.niveau_etudeField
            End Get
            Set(value As CritereReferentiel)
                Me.niveau_etudeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property metier() As CritereReferentiel
            Get
                Return Me.metierField
            End Get
            Set(value As CritereReferentiel)
                Me.metierField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("mobilite")> _
        Public Property mobilite() As CritereReferentiel()
            Get
                Return Me.mobiliteField
            End Get
            Set(value As CritereReferentiel())
                Me.mobiliteField = value
            End Set
        End Property

        '''<remarks/>
        Public Property date_debut() As CritereDate
            Get
                Return Me.date_debutField
            End Get
            Set(value As CritereDate)
                Me.date_debutField = value
            End Set
        End Property

        '''<remarks/>
        Public Property date_fin() As CritereDate
            Get
                Return Me.date_finField
            End Get
            Set(value As CritereDate)
                Me.date_finField = value
            End Set
        End Property

        '''<remarks/>
        Public Property permis() As CritereReferentiel
            Get
                Return Me.permisField
            End Get
            Set(value As CritereReferentiel)
                Me.permisField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("competence")> _
        Public Property competence() As CritereReferentiel()
            Get
                Return Me.competenceField
            End Get
            Set(value As CritereReferentiel())
                Me.competenceField = value
            End Set
        End Property

        '''<remarks/>
        Public Property annees_experience() As CritereFloat
            Get
                Return Me.annees_experienceField
            End Get
            Set(value As CritereFloat)
                Me.annees_experienceField = value
            End Set
        End Property

        '''<remarks/>
        Public Property client() As CritereReferentiel
            Get
                Return Me.clientField
            End Get
            Set(value As CritereReferentiel)
                Me.clientField = value
            End Set
        End Property

        '''<remarks/>
        Public Property secteur() As CritereReferentiel
            Get
                Return Me.secteurField
            End Get
            Set(value As CritereReferentiel)
                Me.secteurField = value
            End Set
        End Property

        '''<remarks/>
        Public Property service() As CritereReferentiel
            Get
                Return Me.serviceField
            End Get
            Set(value As CritereReferentiel)
                Me.serviceField = value
            End Set
        End Property

        '''<remarks/>
        Public Property regroupement() As CritereReferentiel
            Get
                Return Me.regroupementField
            End Get
            Set(value As CritereReferentiel)
                Me.regroupementField = value
            End Set
        End Property

        '''<remarks/>
        Public Property diplome() As CritereDiplome
            Get
                Return Me.diplomeField
            End Get
            Set(value As CritereDiplome)
                Me.diplomeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("habilitation")> _
        Public Property habilitation() As CritereHabilitation()
            Get
                Return Me.habilitationField
            End Get
            Set(value As CritereHabilitation())
                Me.habilitationField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("langue")> _
        Public Property langue() As CritereReferentiel()
            Get
                Return Me.langueField
            End Get
            Set(value As CritereReferentiel())
                Me.langueField = value
            End Set
        End Property

        '''<remarks/>
        Public Property visite_medicale_a_jour() As CritereDate
            Get
                Return Me.visite_medicale_a_jourField
            End Get
            Set(value As CritereDate)
                Me.visite_medicale_a_jourField = value
            End Set
        End Property

        '''<remarks/>
        Public Property statut_cdi_tt() As CritereFlag
            Get
                Return Me.statut_cdi_ttField
            End Get
            Set(value As CritereFlag)
                Me.statut_cdi_ttField = value
            End Set
        End Property

        '''<remarks/>
        Public Property tt_400h() As CritereFlag
            Get
                Return Me.tt_400hField
            End Get
            Set(value As CritereFlag)
                Me.tt_400hField = value
            End Set
        End Property

        '''<remarks/>
        Public Property fspi() As CritereFlag
            Get
                Return Me.fspiField
            End Get
            Set(value As CritereFlag)
                Me.fspiField = value
            End Set
        End Property

        '''<remarks/>
        Public Property compte() As Compte
            Get
                Return Me.compteField
            End Get
            Set(value As Compte)
                Me.compteField = value
            End Set
        End Property

        '''<remarks/>
        Public Property adresse_delegation() As Adresse
            Get
                Return Me.adresse_delegationField
            End Get
            Set(value As Adresse)
                Me.adresse_delegationField = value
            End Set
        End Property

        '''<remarks/>
        Public Property cp_commune() As Referentiel
            Get
                Return Me.cp_communeField
            End Get
            Set(value As Referentiel)
                Me.cp_communeField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/CLIENTSchema.xsd")> _
    Partial Public Class Sections

        Private employerDescriptionField As String

        Private jobDescriptionField As String

        Private candidateProfileField As String

        Private conditionsBenefitsField As String

        Private applicationProcedureField As String

        '''<remarks/>
        Public Property EmployerDescription() As String
            Get
                Return Me.employerDescriptionField
            End Get
            Set(value As String)
                Me.employerDescriptionField = value
            End Set
        End Property

        '''<remarks/>
        Public Property JobDescription() As String
            Get
                Return Me.jobDescriptionField
            End Get
            Set(value As String)
                Me.jobDescriptionField = value
            End Set
        End Property

        '''<remarks/>
        Public Property CandidateProfile() As String
            Get
                Return Me.candidateProfileField
            End Get
            Set(value As String)
                Me.candidateProfileField = value
            End Set
        End Property

        '''<remarks/>
        Public Property ConditionsBenefits() As String
            Get
                Return Me.conditionsBenefitsField
            End Get
            Set(value As String)
                Me.conditionsBenefitsField = value
            End Set
        End Property

        '''<remarks/>
        Public Property ApplicationProcedure() As String
            Get
                Return Me.applicationProcedureField
            End Get
            Set(value As String)
                Me.applicationProcedureField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/CLIENTSchema.xsd")> _
    Partial Public Class ConditionsBenefits

        Private contractTypeField As String

        Private employmentTypeField As String

        Private hoursPerWeekField As String

        Private workingHoursField As String

        Private salaryField As String

        '''<remarks/>
        Public Property ContractType() As String
            Get
                Return Me.contractTypeField
            End Get
            Set(value As String)
                Me.contractTypeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property EmploymentType() As String
            Get
                Return Me.employmentTypeField
            End Get
            Set(value As String)
                Me.employmentTypeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property HoursPerWeek() As String
            Get
                Return Me.hoursPerWeekField
            End Get
            Set(value As String)
                Me.hoursPerWeekField = value
            End Set
        End Property

        '''<remarks/>
        Public Property WorkingHours() As String
            Get
                Return Me.workingHoursField
            End Get
            Set(value As String)
                Me.workingHoursField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Salary() As String
            Get
                Return Me.salaryField
            End Get
            Set(value As String)
                Me.salaryField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/CLIENTSchema.xsd")> _
    Partial Public Class CandidateRequirements

        Private experienceField As String

        Private educationField As String

        Private competencesField As String

        Private computerSkillsField As String

        Private drivingLicensesField As String

        Private languageSkillsField As String

        '''<remarks/>
        Public Property Experience() As String
            Get
                Return Me.experienceField
            End Get
            Set(value As String)
                Me.experienceField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Education() As String
            Get
                Return Me.educationField
            End Get
            Set(value As String)
                Me.educationField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Competences() As String
            Get
                Return Me.competencesField
            End Get
            Set(value As String)
                Me.competencesField = value
            End Set
        End Property

        '''<remarks/>
        Public Property ComputerSkills() As String
            Get
                Return Me.computerSkillsField
            End Get
            Set(value As String)
                Me.computerSkillsField = value
            End Set
        End Property

        '''<remarks/>
        Public Property DrivingLicenses() As String
            Get
                Return Me.drivingLicensesField
            End Get
            Set(value As String)
                Me.drivingLicensesField = value
            End Set
        End Property

        '''<remarks/>
        Public Property LanguageSkills() As String
            Get
                Return Me.languageSkillsField
            End Get
            Set(value As String)
                Me.languageSkillsField = value
            End Set
        End Property
    End Class

End Namespace
